name: html_editor_enhanced_android_fix
description: HTML rich text editor for Android, iOS, and Web, using the Summernote library.
  Enhanced with highly customizable widget-based controls, bug fixes, callbacks, dark mode, and more.
version: 1.0.0+1
homepage: https://github.com/tneotia/html-editor-enhanced

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # webview plugin
  flutter_inappwebview: ^5.8.0
  # plugin to get webview's visible fraction for keyboard height adjustment
  visibility_detector: ^0.4.0+2
  # plugin to get when the keyboard is hidden via back (Android)
  # or "done" (iOS) to reset the editor's height
  flutter_keyboard_visibility: ^6.0.0
  # plugin to show a color picker for foreground/highlight color
  flex_color_picker: ^3.4.1
  # plugin to get files from filesystem
  file_picker: ^8.0.3
  # plugin to show a scrollable number picker for inserting tables
  numberpicker: ^2.1.2
  # plugin to allow dropdowns and dialogs to be interactable when displaying over the editor
  # related to https://github.com/flutter/flutter/issues/54027
  # pinned to 0.9.1 because of issues with CanvasKit in the latest versions
  pointer_interceptor: ^0.10.1+1
  # plugin to help maintain effective Dart standards
  lints: ^4.0.0
  # plugin for @internal annotation
  meta: '>=1.0.0 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - packages/html_editor_enhanced_android_fix/assets/summernote.html
    - packages/html_editor_enhanced_android_fix/assets/summernote-no-plugins.html
    - packages/html_editor_enhanced_android_fix/assets/summernote-lite.min.css
    - packages/html_editor_enhanced_android_fix/assets/summernote-lite-dark.css
    - packages/html_editor_enhanced_android_fix/assets/summernote-lite.min.js
    - packages/html_editor_enhanced_android_fix/assets/jquery.min.js
    - packages/html_editor_enhanced_android_fix/assets/font/summernote.eot
    - packages/html_editor_enhanced_android_fix/assets/font/summernote.ttf
    - packages/html_editor_enhanced_android_fix/assets/plugins/summernote-at-mention/summernote-at-mention.js

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
